const DRAW_BUFFER_CARDINALITY = 255; 
const PRIZE_DISTRIBUTION_BUFFER_CARDINALITY = 8;
const BEACON_PERIOD_SECONDS = 60 * 20; 
const TOKEN_DECIMALS = 6;
const VALIDITY_DURATION = BEACON_PERIOD_SECONDS

module.exports = {
  DRAW_BUFFER_CARDINALITY,
  PRIZE_DISTRIBUTION_BUFFER_CARDINALITY,
  BEACON_PERIOD_SECONDS,
  VALIDITY_DURATION,
  TOKEN_DECIMALS
}
